import argparse

parser = argparse.ArgumentParser()
#parser.add_argument('--dataset', type=str, default='4', help='dataset')
parser.add_argument('--seed', type=int, default=0, help='seed')
parser.add_argument('--division_seed', type=int, default=0, help='division_seed')
parser.add_argument('--model', type=str, default='DASTNet', help='model')
parser.add_argument('--labelrate', type=float, default=23, help='percent')
parser.add_argument('--patience', type=int, default=200, help='patience')
parser.add_argument("--hidden_dim", type=int, default=64)
parser.add_argument("--vec_dim", type=int, default=64)
parser.add_argument("--enc_dim", type=int, default=64)
parser.add_argument("--walk_length", "--wl", type=int, default=8)
parser.add_argument("--num_walks", type=int, default=200)
parser.add_argument("--theta", type=float, default=1)
parser.add_argument("--p", type=float, default=1)
parser.add_argument("--q", type=float, default=1)
parser.add_argument("--learning_rate", "--lr", type=float, default=1e-4)
parser.add_argument("--epochs", type=int, default=100)
parser.add_argument('--device', type=int, default=6, help='CUDA Device')
parser.add_argument("--batch_size", type=int, default=64)
parser.add_argument("--seq_len", type=int, default=12)
parser.add_argument("--pre_len", type=int, default=3)
parser.add_argument("--split_ratio", type=float, default=0.7)
parser.add_argument("--alpha", type=float, default=0.1)
parser.add_argument("--beta", type=float, default=0.2)
parser.add_argument("--normalize", type=bool, default=True)
parser.add_argument('--val', action='store_true', default=False, help='eval')
parser.add_argument('--test', action='store_true', default=False, help='test')
parser.add_argument('--train', action='store_true', default=False, help='train')
parser.add_argument('--etype', type=str, default="gin", choices=["gin"], help='feature type')
parser.add_argument('--metasplit', type=int, default=28, help='days of data to take for meta train-fineTune-Test')

parser.add_argument('--input_dim',type=int, default=1, help='dimension of the single timestamp' )
parser.add_argument('--rnn_units',type=int, default=64, help='dimension of the single timestamp' )
parser.add_argument("--cheby", type=bool, default=True)
parser.add_argument('--cheb_k',type=int, default=2, help='K in chebyshav polinomual' )
parser.add_argument('--num_layers',type=int, default=2, help='number of Dcrnn layers' )
parser.add_argument('--output_dim',type=int, default=1, help='number of output dimension' )
parser.add_argument('--horizon',type=int, default=12, help='tiemstamp to predict' )
parser.add_argument('--adj_filename', type=str, default="data/PeMSD8/distance.csv", help='adj file location')
parser.add_argument('--num_nodes', default=170, type=int)
parser.add_argument('--normalizer', default='std', type=str)
parser.add_argument('--tod', default=False, type=eval)
parser.add_argument('--lr_init', default=0.003, type=float)
parser.add_argument('--dataset', default='PEMSD8', type=str)
parser.add_argument("--column_wise", type=bool, default=False)
parser.add_argument('--test_ratio', default=0.2, type=float)
parser.add_argument('--val_ratio', default=0.2, type=float)
parser.add_argument('--lag',type=int, default=12, help='timestep to use' )
parser.add_argument('--loss_func', default='mae', type=str)
parser.add_argument('--real_value', default=True, type=eval, help = 'use real value for loss calculation')
parser.add_argument('--mem_dim',type=int, default=64, help='timestep to use' )
parser.add_argument('--mem_num',type=int, default=20, help='timestep to use' ) 
parser.add_argument('--embed_dim',type=int, default=20, help='timestep to use' ) 
parser.add_argument('--lr_decay', default=False, type=eval)
parser.add_argument('--model-ema-decay', type=float, default=0.999,
                    help='decay factor for model weights moving average (default: 0.9998)')
parser.add_argument('--debug', default=False, type=eval)
parser.add_argument('--mode', default='train', type=str)
parser.add_argument('--teacher_forcing', default=False, type=bool)
parser.add_argument('--grad_norm', default=False, type=eval)
parser.add_argument('--log_step', default=20, type=int)
parser.add_argument('--early_stop', default=True, type=eval)
parser.add_argument('--early_stop_patience', default=15, type=int)
parser.add_argument('--mae_thresh', default=None, type=eval)
parser.add_argument('--mape_thresh', default=0, type=float)

parser.add_argument('--fine_epochs', default=20, type=int)

parser.add_argument('--update_lr', type=float, help='task-level inner update learning rate', default=0.01)
parser.add_argument('--update_step', type=int, help='task-level inner update steps', default=3)
parser.add_argument('--update_step_test', type=int, help='update steps for finetunning', default=3)

args = parser.parse_args()